//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagrammy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Доставка.
    /// </summary>
    // *** Start programmer edit section *** (Доставка CustomAttributes)

    // *** End programmer edit section *** (Доставка CustomAttributes)
    public enum Доставка
    {
        
        // *** Start programmer edit section *** (Доставка.Самовывоз CustomAttributes)

        // *** End programmer edit section *** (Доставка.Самовывоз CustomAttributes)
        [Caption("Самовывоз")]
        Самовывоз,
        
        // *** Start programmer edit section *** (Доставка.Курьер CustomAttributes)

        // *** End programmer edit section *** (Доставка.Курьер CustomAttributes)
        [Caption("Курьер")]
        Курьер,
    }
}
