//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagrammy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "ФИОЗаказчика as \'Ф и о заказчика\'",
            "АдресЗаказа as \'Адрес заказа\'",
            "СпособПолучения as \'Способ получения\'",
            "ДатаПолучения as \'Дата получения\'"})]
    [AssociatedDetailViewAttribute("ЗаказE", "ТЧЗаказа", "ТЧЗаказаE", true, "", "Т ч заказа", true, new string[] {
            ""})]
    [View("ЗаказL", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "ФИОЗаказчика as \'Ф и о заказчика\'",
            "АдресЗаказа as \'Адрес заказа\'",
            "СпособПолучения as \'Способ получения\'",
            "ДатаПолучения as \'Дата получения\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЗаказа;
        
        private string fФИОЗаказчика;
        
        private string fАдресЗаказа;
        
        private IIS.Diagrammy.Доставка fСпособПолучения;
        
        private System.DateTime fДатаПолучения;
        
        private IIS.Diagrammy.DetailArrayOfТЧЗаказа fТЧЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// АдресЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.АдресЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.АдресЗаказа CustomAttributes)
        [StrLen(255)]
        public virtual string АдресЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Get start)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Get start)
                string result = this.fАдресЗаказа;
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Get end)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Set start)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Set start)
                this.fАдресЗаказа = value;
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Set end)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Set end)
            }
        }
        
        /// <summary>
        /// ДатаПолучения.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаПолучения CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаПолучения CustomAttributes)
        public virtual System.DateTime ДатаПолучения
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаПолучения Get start)

                // *** End programmer edit section *** (Заказ.ДатаПолучения Get start)
                System.DateTime result = this.fДатаПолучения;
                // *** Start programmer edit section *** (Заказ.ДатаПолучения Get end)

                // *** End programmer edit section *** (Заказ.ДатаПолучения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаПолучения Set start)

                // *** End programmer edit section *** (Заказ.ДатаПолучения Set start)
                this.fДатаПолучения = value;
                // *** Start programmer edit section *** (Заказ.ДатаПолучения Set end)

                // *** End programmer edit section *** (Заказ.ДатаПолучения Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)
        public virtual int НомерЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get start)
                int result = this.fНомерЗаказа;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set start)
                this.fНомерЗаказа = value;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set end)
            }
        }
        
        /// <summary>
        /// СпособПолучения.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СпособПолучения CustomAttributes)

        // *** End programmer edit section *** (Заказ.СпособПолучения CustomAttributes)
        public virtual IIS.Diagrammy.Доставка СпособПолучения
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СпособПолучения Get start)

                // *** End programmer edit section *** (Заказ.СпособПолучения Get start)
                IIS.Diagrammy.Доставка result = this.fСпособПолучения;
                // *** Start programmer edit section *** (Заказ.СпособПолучения Get end)

                // *** End programmer edit section *** (Заказ.СпособПолучения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СпособПолучения Set start)

                // *** End programmer edit section *** (Заказ.СпособПолучения Set start)
                this.fСпособПолучения = value;
                // *** Start programmer edit section *** (Заказ.СпособПолучения Set end)

                // *** End programmer edit section *** (Заказ.СпособПолучения Set end)
            }
        }
        
        /// <summary>
        /// ФИОЗаказчика.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ФИОЗаказчика CustomAttributes)

        // *** End programmer edit section *** (Заказ.ФИОЗаказчика CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОЗаказчика
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ФИОЗаказчика Get start)

                // *** End programmer edit section *** (Заказ.ФИОЗаказчика Get start)
                string result = this.fФИОЗаказчика;
                // *** Start programmer edit section *** (Заказ.ФИОЗаказчика Get end)

                // *** End programmer edit section *** (Заказ.ФИОЗаказчика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ФИОЗаказчика Set start)

                // *** End programmer edit section *** (Заказ.ФИОЗаказчика Set start)
                this.fФИОЗаказчика = value;
                // *** Start programmer edit section *** (Заказ.ФИОЗаказчика Set end)

                // *** End programmer edit section *** (Заказ.ФИОЗаказчика Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ТЧЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.ТЧЗаказа CustomAttributes)
        public virtual IIS.Diagrammy.DetailArrayOfТЧЗаказа ТЧЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ТЧЗаказа Get start)

                // *** End programmer edit section *** (Заказ.ТЧЗаказа Get start)
                if ((this.fТЧЗаказа == null))
                {
                    this.fТЧЗаказа = new IIS.Diagrammy.DetailArrayOfТЧЗаказа(this);
                }
                IIS.Diagrammy.DetailArrayOfТЧЗаказа result = this.fТЧЗаказа;
                // *** Start programmer edit section *** (Заказ.ТЧЗаказа Get end)

                // *** End programmer edit section *** (Заказ.ТЧЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ТЧЗаказа Set start)

                // *** End programmer edit section *** (Заказ.ТЧЗаказа Set start)
                this.fТЧЗаказа = value;
                // *** Start programmer edit section *** (Заказ.ТЧЗаказа Set end)

                // *** End programmer edit section *** (Заказ.ТЧЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Diagrammy.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Diagrammy.Заказ));
                }
            }
        }
    }
}
