//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagrammy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Наличие.
    /// </summary>
    // *** Start programmer edit section *** (Наличие CustomAttributes)

    // *** End programmer edit section *** (Наличие CustomAttributes)
    public enum Наличие
    {
        
        // *** Start programmer edit section *** (Наличие.Да CustomAttributes)

        // *** End programmer edit section *** (Наличие.Да CustomAttributes)
        [Caption("Да")]
        Да,
        
        // *** Start programmer edit section *** (Наличие.Нет CustomAttributes)

        // *** End programmer edit section *** (Наличие.Нет CustomAttributes)
        [Caption("Нет")]
        Нет,
    }
}
