//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagrammy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отпуск материала.
    /// </summary>
    // *** Start programmer edit section *** (ОтпускМатериала CustomAttributes)

    // *** End programmer edit section *** (ОтпускМатериала CustomAttributes)
    [AutoAltered()]
    [Caption("Отпуск материала")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтпускМатериалаE", new string[] {
            "ДатаПроводки as \'Дата проводки\'",
            "СкладскоеМесто as \'Складское место\'",
            "СкладскоеМесто.НомерМеста as \'Номер места\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИОСотрудника as \'Ф и о сотрудника\'",
            "Заказ as \'Заказ\'",
            "Заказ.ФИОЗаказчика as \'Ф и о заказчика\'"}, Hidden=new string[] {
            "СкладскоеМесто.НомерМеста",
            "Сотрудники.ФИОСотрудника",
            "Заказ.ФИОЗаказчика"})]
    [MasterViewDefineAttribute("ОтпускМатериалаE", "СкладскоеМесто", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерМеста")]
    [MasterViewDefineAttribute("ОтпускМатериалаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОСотрудника")]
    [MasterViewDefineAttribute("ОтпускМатериалаE", "Заказ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОЗаказчика")]
    [View("ОтпускМатериалаL", new string[] {
            "ДатаПроводки as \'Дата проводки\'",
            "СкладскоеМесто.НомерМеста as \'Номер места\'",
            "Сотрудники.ФИОСотрудника as \'Ф и о сотрудника\'",
            "Заказ.ФИОЗаказчика as \'Ф и о заказчика\'"})]
    public class ОтпускМатериала : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПроводки;
        
        private IIS.Diagrammy.СкладскоеМесто fСкладскоеМесто;
        
        private IIS.Diagrammy.Сотрудники fСотрудники;
        
        private IIS.Diagrammy.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (ОтпускМатериала CustomMembers)

        // *** End programmer edit section *** (ОтпускМатериала CustomMembers)

        
        /// <summary>
        /// ДатаПроводки.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки CustomAttributes)

        // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки CustomAttributes)
        public virtual System.DateTime ДатаПроводки
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки Get start)

                // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки Get start)
                System.DateTime result = this.fДатаПроводки;
                // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки Get end)

                // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки Set start)

                // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки Set start)
                this.fДатаПроводки = value;
                // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки Set end)

                // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки Set end)
            }
        }
        
        /// <summary>
        /// Отпуск материала.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМатериала.Заказ CustomAttributes)

        // *** End programmer edit section *** (ОтпускМатериала.Заказ CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказ"})]
        [NotNull()]
        public virtual IIS.Diagrammy.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМатериала.Заказ Get start)

                // *** End programmer edit section *** (ОтпускМатериала.Заказ Get start)
                IIS.Diagrammy.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (ОтпускМатериала.Заказ Get end)

                // *** End programmer edit section *** (ОтпускМатериала.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМатериала.Заказ Set start)

                // *** End programmer edit section *** (ОтпускМатериала.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (ОтпускМатериала.Заказ Set end)

                // *** End programmer edit section *** (ОтпускМатериала.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Отпуск материала.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМатериала.СкладскоеМесто CustomAttributes)

        // *** End programmer edit section *** (ОтпускМатериала.СкладскоеМесто CustomAttributes)
        [PropertyStorage(new string[] {
                "СкладскоеМесто"})]
        [NotNull()]
        public virtual IIS.Diagrammy.СкладскоеМесто СкладскоеМесто
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМатериала.СкладскоеМесто Get start)

                // *** End programmer edit section *** (ОтпускМатериала.СкладскоеМесто Get start)
                IIS.Diagrammy.СкладскоеМесто result = this.fСкладскоеМесто;
                // *** Start programmer edit section *** (ОтпускМатериала.СкладскоеМесто Get end)

                // *** End programmer edit section *** (ОтпускМатериала.СкладскоеМесто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМатериала.СкладскоеМесто Set start)

                // *** End programmer edit section *** (ОтпускМатериала.СкладскоеМесто Set start)
                this.fСкладскоеМесто = value;
                // *** Start programmer edit section *** (ОтпускМатериала.СкладскоеМесто Set end)

                // *** End programmer edit section *** (ОтпускМатериала.СкладскоеМесто Set end)
            }
        }
        
        /// <summary>
        /// Отпуск материала.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМатериала.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтпускМатериала.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Diagrammy.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМатериала.Сотрудники Get start)

                // *** End programmer edit section *** (ОтпускМатериала.Сотрудники Get start)
                IIS.Diagrammy.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтпускМатериала.Сотрудники Get end)

                // *** End programmer edit section *** (ОтпускМатериала.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМатериала.Сотрудники Set start)

                // *** End programmer edit section *** (ОтпускМатериала.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтпускМатериала.Сотрудники Set end)

                // *** End programmer edit section *** (ОтпускМатериала.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтпускМатериалаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтпускМатериалаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтпускМатериалаE", typeof(IIS.Diagrammy.ОтпускМатериала));
                }
            }
            
            /// <summary>
            /// "ОтпускМатериалаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтпускМатериалаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтпускМатериалаL", typeof(IIS.Diagrammy.ОтпускМатериала));
                }
            }
        }
    }
}
