//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagrammy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Поставщики.
    /// </summary>
    // *** Start programmer edit section *** (Поставщики CustomAttributes)

    // *** End programmer edit section *** (Поставщики CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоставщикиE", new string[] {
            "КодПоставщика as \'Код поставщика\'",
            "Наименование as \'Наименование\'",
            "НомерТС as \'Номер ТС\'"})]
    [View("ПоставщикиL", new string[] {
            "КодПоставщика as \'Код поставщика\'",
            "Наименование as \'Наименование\'",
            "НомерТС as \'Номер ТС\'"})]
    public class Поставщики : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодПоставщика;
        
        private string fНаименование;
        
        private string fНомерТС;
        
        // *** Start programmer edit section *** (Поставщики CustomMembers)

        // *** End programmer edit section *** (Поставщики CustomMembers)

        
        /// <summary>
        /// КодПоставщика.
        /// </summary>
        // *** Start programmer edit section *** (Поставщики.КодПоставщика CustomAttributes)

        // *** End programmer edit section *** (Поставщики.КодПоставщика CustomAttributes)
        public virtual int КодПоставщика
        {
            get
            {
                // *** Start programmer edit section *** (Поставщики.КодПоставщика Get start)

                // *** End programmer edit section *** (Поставщики.КодПоставщика Get start)
                int result = this.fКодПоставщика;
                // *** Start programmer edit section *** (Поставщики.КодПоставщика Get end)

                // *** End programmer edit section *** (Поставщики.КодПоставщика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставщики.КодПоставщика Set start)

                // *** End programmer edit section *** (Поставщики.КодПоставщика Set start)
                this.fКодПоставщика = value;
                // *** Start programmer edit section *** (Поставщики.КодПоставщика Set end)

                // *** End programmer edit section *** (Поставщики.КодПоставщика Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Поставщики.Наименование CustomAttributes)

        // *** End programmer edit section *** (Поставщики.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Поставщики.Наименование Get start)

                // *** End programmer edit section *** (Поставщики.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Поставщики.Наименование Get end)

                // *** End programmer edit section *** (Поставщики.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставщики.Наименование Set start)

                // *** End programmer edit section *** (Поставщики.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Поставщики.Наименование Set end)

                // *** End programmer edit section *** (Поставщики.Наименование Set end)
            }
        }
        
        /// <summary>
        /// НомерТС.
        /// </summary>
        // *** Start programmer edit section *** (Поставщики.НомерТС CustomAttributes)

        // *** End programmer edit section *** (Поставщики.НомерТС CustomAttributes)
        [StrLen(255)]
        public virtual string НомерТС
        {
            get
            {
                // *** Start programmer edit section *** (Поставщики.НомерТС Get start)

                // *** End programmer edit section *** (Поставщики.НомерТС Get start)
                string result = this.fНомерТС;
                // *** Start programmer edit section *** (Поставщики.НомерТС Get end)

                // *** End programmer edit section *** (Поставщики.НомерТС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставщики.НомерТС Set start)

                // *** End programmer edit section *** (Поставщики.НомерТС Set start)
                this.fНомерТС = value;
                // *** Start programmer edit section *** (Поставщики.НомерТС Set end)

                // *** End programmer edit section *** (Поставщики.НомерТС Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоставщикиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставщикиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставщикиE", typeof(IIS.Diagrammy.Поставщики));
                }
            }
            
            /// <summary>
            /// "ПоставщикиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставщикиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставщикиL", typeof(IIS.Diagrammy.Поставщики));
                }
            }
        }
    }
}
