//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagrammy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "ФИОСотрудника as \'Ф и о сотрудника\'",
            "Должность as \'Должность\'",
            "Табель as \'Табель\'"})]
    [View("СотрудникиL", new string[] {
            "ФИОСотрудника as \'Ф и о сотрудника\'",
            "Должность as \'Должность\'",
            "Табель as \'Табель\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИОСотрудника;
        
        private string fДолжность;
        
        private int fТабель;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должность CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Get start)

                // *** End programmer edit section *** (Сотрудники.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (Сотрудники.Должность Get end)

                // *** End programmer edit section *** (Сотрудники.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Set start)

                // *** End programmer edit section *** (Сотрудники.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Сотрудники.Должность Set end)

                // *** End programmer edit section *** (Сотрудники.Должность Set end)
            }
        }
        
        /// <summary>
        /// Табель.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Табель CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Табель CustomAttributes)
        public virtual int Табель
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Табель Get start)

                // *** End programmer edit section *** (Сотрудники.Табель Get start)
                int result = this.fТабель;
                // *** Start programmer edit section *** (Сотрудники.Табель Get end)

                // *** End programmer edit section *** (Сотрудники.Табель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Табель Set start)

                // *** End programmer edit section *** (Сотрудники.Табель Set start)
                this.fТабель = value;
                // *** Start programmer edit section *** (Сотрудники.Табель Set end)

                // *** End programmer edit section *** (Сотрудники.Табель Set end)
            }
        }
        
        /// <summary>
        /// ФИОСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ФИОСотрудника CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Get start)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Get start)
                string result = this.fФИОСотрудника;
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Get end)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Set start)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Set start)
                this.fФИОСотрудника = value;
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Set end)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Diagrammy.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Diagrammy.Сотрудники));
                }
            }
        }
    }
}
