//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagrammy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "КодМатериала as \'Код материала\'",
            "Материал as \'Материал\'",
            "Цена as \'Цена\'",
            "ЕстьВНаличии as \'Есть в наличии\'",
            "Количество as \'Количество\'",
            "СкладскоеМесто as \'Складское место\'",
            "СкладскоеМесто.НомерМеста as \'Номер места\'"}, Hidden=new string[] {
            "СкладскоеМесто.НомерМеста"})]
    [MasterViewDefineAttribute("ТоварE", "СкладскоеМесто", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерМеста")]
    [View("ТоварL", new string[] {
            "КодМатериала as \'Код материала\'",
            "Материал as \'Материал\'",
            "Цена as \'Цена\'",
            "ЕстьВНаличии as \'Есть в наличии\'",
            "Количество as \'Количество\'",
            "СкладскоеМесто.НомерМеста as \'Номер места\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодМатериала;
        
        private string fМатериал;
        
        private double fЦена;
        
        private int fКоличество;
        
        private IIS.Diagrammy.Наличие fЕстьВНаличии;
        
        private IIS.Diagrammy.СкладскоеМесто fСкладскоеМесто;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// ЕстьВНаличии.
        /// </summary>
        // *** Start programmer edit section *** (Товар.ЕстьВНаличии CustomAttributes)

        // *** End programmer edit section *** (Товар.ЕстьВНаличии CustomAttributes)
        public virtual IIS.Diagrammy.Наличие ЕстьВНаличии
        {
            get
            {
                // *** Start programmer edit section *** (Товар.ЕстьВНаличии Get start)

                // *** End programmer edit section *** (Товар.ЕстьВНаличии Get start)
                IIS.Diagrammy.Наличие result = this.fЕстьВНаличии;
                // *** Start programmer edit section *** (Товар.ЕстьВНаличии Get end)

                // *** End programmer edit section *** (Товар.ЕстьВНаличии Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.ЕстьВНаличии Set start)

                // *** End programmer edit section *** (Товар.ЕстьВНаличии Set start)
                this.fЕстьВНаличии = value;
                // *** Start programmer edit section *** (Товар.ЕстьВНаличии Set end)

                // *** End programmer edit section *** (Товар.ЕстьВНаличии Set end)
            }
        }
        
        /// <summary>
        /// КодМатериала.
        /// </summary>
        // *** Start programmer edit section *** (Товар.КодМатериала CustomAttributes)

        // *** End programmer edit section *** (Товар.КодМатериала CustomAttributes)
        public virtual int КодМатериала
        {
            get
            {
                // *** Start programmer edit section *** (Товар.КодМатериала Get start)

                // *** End programmer edit section *** (Товар.КодМатериала Get start)
                int result = this.fКодМатериала;
                // *** Start programmer edit section *** (Товар.КодМатериала Get end)

                // *** End programmer edit section *** (Товар.КодМатериала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.КодМатериала Set start)

                // *** End programmer edit section *** (Товар.КодМатериала Set start)
                this.fКодМатериала = value;
                // *** Start programmer edit section *** (Товар.КодМатериала Set end)

                // *** End programmer edit section *** (Товар.КодМатериала Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Количество CustomAttributes)

        // *** End programmer edit section *** (Товар.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Количество Get start)

                // *** End programmer edit section *** (Товар.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Товар.Количество Get end)

                // *** End programmer edit section *** (Товар.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Количество Set start)

                // *** End programmer edit section *** (Товар.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Товар.Количество Set end)

                // *** End programmer edit section *** (Товар.Количество Set end)
            }
        }
        
        /// <summary>
        /// Материал.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Материал CustomAttributes)

        // *** End programmer edit section *** (Товар.Материал CustomAttributes)
        [StrLen(255)]
        public virtual string Материал
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Материал Get start)

                // *** End programmer edit section *** (Товар.Материал Get start)
                string result = this.fМатериал;
                // *** Start programmer edit section *** (Товар.Материал Get end)

                // *** End programmer edit section *** (Товар.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Материал Set start)

                // *** End programmer edit section *** (Товар.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (Товар.Материал Set end)

                // *** End programmer edit section *** (Товар.Материал Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Цена CustomAttributes)

        // *** End programmer edit section *** (Товар.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Цена Get start)

                // *** End programmer edit section *** (Товар.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Товар.Цена Get end)

                // *** End programmer edit section *** (Товар.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Цена Set start)

                // *** End programmer edit section *** (Товар.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Товар.Цена Set end)

                // *** End programmer edit section *** (Товар.Цена Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Товар.СкладскоеМесто CustomAttributes)

        // *** End programmer edit section *** (Товар.СкладскоеМесто CustomAttributes)
        [PropertyStorage(new string[] {
                "СкладскоеМесто"})]
        [NotNull()]
        public virtual IIS.Diagrammy.СкладскоеМесто СкладскоеМесто
        {
            get
            {
                // *** Start programmer edit section *** (Товар.СкладскоеМесто Get start)

                // *** End programmer edit section *** (Товар.СкладскоеМесто Get start)
                IIS.Diagrammy.СкладскоеМесто result = this.fСкладскоеМесто;
                // *** Start programmer edit section *** (Товар.СкладскоеМесто Get end)

                // *** End programmer edit section *** (Товар.СкладскоеМесто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.СкладскоеМесто Set start)

                // *** End programmer edit section *** (Товар.СкладскоеМесто Set start)
                this.fСкладскоеМесто = value;
                // *** Start programmer edit section *** (Товар.СкладскоеМесто Set end)

                // *** End programmer edit section *** (Товар.СкладскоеМесто Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.Diagrammy.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.Diagrammy.Товар));
                }
            }
        }
    }
}
