//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagrammy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч заказа.
    /// </summary>
    // *** Start programmer edit section *** (ТЧЗаказа CustomAttributes)

    // *** End programmer edit section *** (ТЧЗаказа CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧЗаказаE", new string[] {
            "Количество as \'Количество\'",
            "Товар as \'Товар\'",
            "Товар.Материал as \'Материал\'"}, Hidden=new string[] {
            "Товар.Материал"})]
    [MasterViewDefineAttribute("ТЧЗаказаE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Материал")]
    public class ТЧЗаказа : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Diagrammy.Товар fТовар;
        
        private IIS.Diagrammy.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (ТЧЗаказа CustomMembers)

        // *** End programmer edit section *** (ТЧЗаказа CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧЗаказа.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧЗаказа.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧЗаказа.Количество Get start)

                // *** End programmer edit section *** (ТЧЗаказа.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧЗаказа.Количество Get end)

                // *** End programmer edit section *** (ТЧЗаказа.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧЗаказа.Количество Set start)

                // *** End programmer edit section *** (ТЧЗаказа.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧЗаказа.Количество Set end)

                // *** End programmer edit section *** (ТЧЗаказа.Количество Set end)
            }
        }
        
        /// <summary>
        /// Т ч заказа.
        /// </summary>
        // *** Start programmer edit section *** (ТЧЗаказа.Товар CustomAttributes)

        // *** End programmer edit section *** (ТЧЗаказа.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Diagrammy.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (ТЧЗаказа.Товар Get start)

                // *** End programmer edit section *** (ТЧЗаказа.Товар Get start)
                IIS.Diagrammy.Товар result = this.fТовар;
                // *** Start programmer edit section *** (ТЧЗаказа.Товар Get end)

                // *** End programmer edit section *** (ТЧЗаказа.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧЗаказа.Товар Set start)

                // *** End programmer edit section *** (ТЧЗаказа.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ТЧЗаказа.Товар Set end)

                // *** End programmer edit section *** (ТЧЗаказа.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Diagrammy.Заказ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧЗаказа.Заказ CustomAttributes)

        // *** End programmer edit section *** (ТЧЗаказа.Заказ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказ"})]
        public virtual IIS.Diagrammy.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (ТЧЗаказа.Заказ Get start)

                // *** End programmer edit section *** (ТЧЗаказа.Заказ Get start)
                IIS.Diagrammy.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (ТЧЗаказа.Заказ Get end)

                // *** End programmer edit section *** (ТЧЗаказа.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧЗаказа.Заказ Set start)

                // *** End programmer edit section *** (ТЧЗаказа.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (ТЧЗаказа.Заказ Set end)

                // *** End programmer edit section *** (ТЧЗаказа.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧЗаказаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧЗаказаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧЗаказаE", typeof(IIS.Diagrammy.ТЧЗаказа));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧЗаказа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧЗаказа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧЗаказа CustomAttributes)
    public class DetailArrayOfТЧЗаказа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Diagrammy.DetailArrayOfТЧЗаказа members)

        // *** End programmer edit section *** (IIS.Diagrammy.DetailArrayOfТЧЗаказа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧЗаказа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧЗаказа.
        /// </summary>
        public DetailArrayOfТЧЗаказа(IIS.Diagrammy.Заказ fЗаказ) : 
                base(typeof(ТЧЗаказа), ((ICSSoft.STORMNET.DataObject)(fЗаказ)))
        {
        }
        
        public IIS.Diagrammy.ТЧЗаказа this[int index]
        {
            get
            {
                return ((IIS.Diagrammy.ТЧЗаказа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Diagrammy.ТЧЗаказа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
