//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagrammy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч акта приемки.
    /// </summary>
    // *** Start programmer edit section *** (ТЧАктаПриемки CustomAttributes)

    // *** End programmer edit section *** (ТЧАктаПриемки CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч акта приемки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧАктаПриемкиE", new string[] {
            "Товар as \'Товар\'",
            "Товар.Материал as \'Материал\'",
            "Количество as \'Количество\'",
            "СкладскоеМесто as \'Складское место\'",
            "СкладскоеМесто.НомерМеста as \'Номер места\'"}, Hidden=new string[] {
            "Товар.Материал",
            "СкладскоеМесто.НомерМеста"})]
    [MasterViewDefineAttribute("ТЧАктаПриемкиE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Материал")]
    [MasterViewDefineAttribute("ТЧАктаПриемкиE", "СкладскоеМесто", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерМеста")]
    public class ТЧАктаПриемки : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Diagrammy.СкладскоеМесто fСкладскоеМесто;
        
        private IIS.Diagrammy.Товар fТовар;
        
        private IIS.Diagrammy.АктПриемки fАктПриемки;
        
        // *** Start programmer edit section *** (ТЧАктаПриемки CustomMembers)

        // *** End programmer edit section *** (ТЧАктаПриемки CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Количество Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Количество Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Количество Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Количество Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Количество Set end)
            }
        }
        
        /// <summary>
        /// Т ч акта приемки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто CustomAttributes)
        [PropertyStorage(new string[] {
                "СкладскоеМесто"})]
        [NotNull()]
        public virtual IIS.Diagrammy.СкладскоеМесто СкладскоеМесто
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто Get start)
                IIS.Diagrammy.СкладскоеМесто result = this.fСкладскоеМесто;
                // *** Start programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто Set start)
                this.fСкладскоеМесто = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.СкладскоеМесто Set end)
            }
        }
        
        /// <summary>
        /// Т ч акта приемки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.Товар CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Diagrammy.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Товар Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Товар Get start)
                IIS.Diagrammy.Товар result = this.fТовар;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Товар Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Товар Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Товар Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Diagrammy.АктПриемки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.АктПриемки CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.АктПриемки CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "АктПриемки"})]
        public virtual IIS.Diagrammy.АктПриемки АктПриемки
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.АктПриемки Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.АктПриемки Get start)
                IIS.Diagrammy.АктПриемки result = this.fАктПриемки;
                // *** Start programmer edit section *** (ТЧАктаПриемки.АктПриемки Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.АктПриемки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.АктПриемки Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.АктПриемки Set start)
                this.fАктПриемки = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.АктПриемки Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.АктПриемки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧАктаПриемкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧАктаПриемкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧАктаПриемкиE", typeof(IIS.Diagrammy.ТЧАктаПриемки));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧАктаПриемки.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧАктаПриемки CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧАктаПриемки CustomAttributes)
    public class DetailArrayOfТЧАктаПриемки : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Diagrammy.DetailArrayOfТЧАктаПриемки members)

        // *** End programmer edit section *** (IIS.Diagrammy.DetailArrayOfТЧАктаПриемки members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧАктаПриемки by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧАктаПриемки.
        /// </summary>
        public DetailArrayOfТЧАктаПриемки(IIS.Diagrammy.АктПриемки fАктПриемки) : 
                base(typeof(ТЧАктаПриемки), ((ICSSoft.STORMNET.DataObject)(fАктПриемки)))
        {
        }
        
        public IIS.Diagrammy.ТЧАктаПриемки this[int index]
        {
            get
            {
                return ((IIS.Diagrammy.ТЧАктаПриемки)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Diagrammy.ТЧАктаПриемки dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
